# Generated by Django 4.1.1 on 2022-11-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("add_date", models.DateField(auto_created=True, null=True)),
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="category/")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("Post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post/")),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="new.category"
                    ),
                ),
            ],
        ),
    ]
